name: Rust

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: wasm-pack-action
    - name: test
      run: cargo test --verbose
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
    - name: Build
      run: cargo install wasm-pack && ./build.sh
        
