name: Rust

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update local toolchain
      run: |
        rustup update
        rustup component add clippy
        rustup install nightly   
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version 
    - name: Add wasm support
      run: rustup target add wasm32-unknown-unknown
#     - uses: jetli/wasm-pack-action@v0.3.0
    - name: check files
      run: ls -R
    - name: test
      run: cargo test --verbose
      
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - uses: jetli/wasm-pack-action@v0.3.0
#     - name: Build
#       run: cargo install wasm-pack && ./build.sh
        
